name: CD - Deploy with Terraform

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag to Deploy (e.g., commit SHA)'
        required: true
        default: 'latest'

env:
  TF_WORKING_DIR: ./docker/terraform
  IMAGE_NAME: zayn63/strapi

jobs:
  terraform-deploy:
    name: Apply Terraform to Deploy EC2 with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -var="image_name=${{ env.IMAGE_NAME }}" -var="image_tag=${{ github.event.inputs.image_tag }}"

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve -var="image_name=${{ env.IMAGE_NAME }}" -var="image_tag=${{ github.event.inputs.image_tag }}"

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1  # Change if using a different region
